### ISSUE TITLE
Warnings coming from homebrew-update-notifier's formula

### ISSUE THREAD

**Issue by borisceranic** [rwoeber/homebrew-update-notifier#2]
Invoking `brew info homebrew-update-notifier` triggers warnings, as well as doing `brew update`, and so on.

```
Warning: Calling Formula.sha1 is deprecated!
Use Formula.sha256 instead.
/Users/boris/Library/Caches/Homebrew/Formula/homebrew-update-notifier.rb:5:in `<class:HomebrewUpdateNotifier>'

Warning: Calling SoftwareSpec#sha1 is deprecated!
Use SoftwareSpec#sha256 instead.
/Users/boris/Library/Caches/Homebrew/Formula/homebrew-update-notifier.rb:5:in `<class:HomebrewUpdateNotifier>'

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/Users/boris/Library/Caches/Homebrew/Formula/homebrew-update-notifier.rb:5:in `<class:HomebrewUpdateNotifier>'
```

**Comment by rwoeber** [comment]
Shot myself in the foot apparently with putting the install script into the same repository as the project itself – so I didn’t tag a new version.
Anyway, I put the SHA256 into the install script. Since this is not an official formula and there is no tap, `brew update` will not update the formula (install script) and will have to manually do this yourself:

Re-Installing (`brew install https…otifier.rb`) should be the easiest way (no need to uninstall, will bring a warning about already installed, though).

**Comment by frdmn** [comment]
This can be closed, I guess 👍

**Comment by frdmn** [comment]
@borisceranic Feel free to reply here in case this problem still occurs for you.
